#!/usr/bin/env bash
rm -r ~/.config/nvim
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua/theprimeagen

# link wholesale
for f in `gfind . -regex ".*\.vim$\|.*\.lua$"`; do
    echo $f
    rm -rf ~/.config/nvim/$f
    ln -s ~/dotfiles/awesome-streamerrc/ThePrimeagen/$f ~/.config/nvim/$f
done

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

